# Generated by Django 3.0.5 on 2020-04-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournment',
            old_name='tounrnment_name',
            new_name='tournment_name',
        ),
    ]
